#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thriftlib.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *
from thriftlib.Thrift import TProcessor
from thriftlib.transport import TTransport
from thriftlib.protocol import TBinaryProtocol, TProtocol
try:
  from thriftlib.protocol import fastbinary
except:
  fastbinary = None


class Iface:
  def registerParticipant(self, coorContext, protocolIdentifier, participantEPR):
    """
    Parameters:
     - coorContext
     - protocolIdentifier
     - participantEPR
    """
    pass


class Client(Iface):
  def __init__(self, iprot, oprot=None):
    self._iprot = self._oprot = iprot
    if oprot is not None:
      self._oprot = oprot
    self._seqid = 0

  def registerParticipant(self, coorContext, protocolIdentifier, participantEPR):
    """
    Parameters:
     - coorContext
     - protocolIdentifier
     - participantEPR
    """
    self.send_registerParticipant(coorContext, protocolIdentifier, participantEPR)
    return self.recv_registerParticipant()

  def send_registerParticipant(self, coorContext, protocolIdentifier, participantEPR):
    self._oprot.writeMessageBegin('registerParticipant', TMessageType.CALL, self._seqid)
    args = registerParticipant_args()
    args.coorContext = coorContext
    args.protocolIdentifier = protocolIdentifier
    args.participantEPR = participantEPR
    args.write(self._oprot)
    self._oprot.writeMessageEnd()
    self._oprot.trans.flush()

  def recv_registerParticipant(self, ):
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
    if mtype == TMessageType.EXCEPTION:
      x = TApplicationException()
      x.read(self._iprot)
      self._iprot.readMessageEnd()
      raise x
    result = registerParticipant_result()
    result.read(self._iprot)
    self._iprot.readMessageEnd()
    if result.success is not None:
      return result.success
    raise TApplicationException(TApplicationException.MISSING_RESULT, "registerParticipant failed: unknown result");


class Processor(Iface, TProcessor):
  def __init__(self, handler):
    self._handler = handler
    self._processMap = {}
    self._processMap["registerParticipant"] = Processor.process_registerParticipant

  def process(self, iprot, oprot):
    (name, type, seqid) = iprot.readMessageBegin()
    if name not in self._processMap:
      iprot.skip(TType.STRUCT)
      iprot.readMessageEnd()
      x = TApplicationException(TApplicationException.UNKNOWN_METHOD, 'Unknown function %s' % (name))
      oprot.writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
      x.write(oprot)
      oprot.writeMessageEnd()
      oprot.trans.flush()
      return
    else:
      self._processMap[name](self, seqid, iprot, oprot)
    return True

  def process_registerParticipant(self, seqid, iprot, oprot):
    args = registerParticipant_args()
    args.read(iprot)
    iprot.readMessageEnd()
    result = registerParticipant_result()
    result.success = self._handler.registerParticipant(args.coorContext, args.protocolIdentifier, args.participantEPR)
    oprot.writeMessageBegin("registerParticipant", TMessageType.REPLY, seqid)
    result.write(oprot)
    oprot.writeMessageEnd()
    oprot.trans.flush()


# HELPER FUNCTIONS AND STRUCTURES

class registerParticipant_args:
  """
  Attributes:
   - coorContext
   - protocolIdentifier
   - participantEPR
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRUCT, 'coorContext', (CoordinationContext, CoordinationContext.thrift_spec), None, ), # 1
    (2, TType.STRING, 'protocolIdentifier', None, None, ), # 2
    (3, TType.STRUCT, 'participantEPR', (EndPointReference, EndPointReference.thrift_spec), None, ), # 3
  )

  def __init__(self, coorContext=None, protocolIdentifier=None, participantEPR=None,):
    self.coorContext = coorContext
    self.protocolIdentifier = protocolIdentifier
    self.participantEPR = participantEPR

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRUCT:
          self.coorContext = CoordinationContext()
          self.coorContext.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.protocolIdentifier = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRUCT:
          self.participantEPR = EndPointReference()
          self.participantEPR.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('registerParticipant_args')
    if self.coorContext is not None:
      oprot.writeFieldBegin('coorContext', TType.STRUCT, 1)
      self.coorContext.write(oprot)
      oprot.writeFieldEnd()
    if self.protocolIdentifier is not None:
      oprot.writeFieldBegin('protocolIdentifier', TType.STRING, 2)
      oprot.writeString(self.protocolIdentifier)
      oprot.writeFieldEnd()
    if self.participantEPR is not None:
      oprot.writeFieldBegin('participantEPR', TType.STRUCT, 3)
      self.participantEPR.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class registerParticipant_result:
  """
  Attributes:
   - success
  """

  thrift_spec = (
    (0, TType.BOOL, 'success', None, None, ), # 0
  )

  def __init__(self, success=None,):
    self.success = success

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 0:
        if ftype == TType.BOOL:
          self.success = iprot.readBool();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('registerParticipant_result')
    if self.success is not None:
      oprot.writeFieldBegin('success', TType.BOOL, 0)
      oprot.writeBool(self.success)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
