
package org.wso2.carbon.registry.acidothinterface.registrationservie_wsdl;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RegistrationServiceImplService", targetNamespace = "http://registration.server/")
public class RegistrationServiceImplService
    extends Service
{

    private final static URL REGISTRATIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException REGISTRATIONSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName REGISTRATIONSERVICEIMPLSERVICE_QNAME = new QName("http://registration.server/", "RegistrationServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8083/RegistrationServie?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REGISTRATIONSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        REGISTRATIONSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public RegistrationServiceImplService() {
        super(__getWsdlLocation(), REGISTRATIONSERVICEIMPLSERVICE_QNAME);
    }

    public RegistrationServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGISTRATIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public RegistrationServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, REGISTRATIONSERVICEIMPLSERVICE_QNAME);
    }

    public RegistrationServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGISTRATIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public RegistrationServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistrationServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RegistrationService
     */
    @WebEndpoint(name = "RegistrationServiceImplPort")
    public RegistrationService getRegistrationServiceImplPort() {
        return super.getPort(new QName("http://registration.server/", "RegistrationServiceImplPort"), RegistrationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistrationService
     */
    @WebEndpoint(name = "RegistrationServiceImplPort")
    public RegistrationService getRegistrationServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://registration.server/", "RegistrationServiceImplPort"), RegistrationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGISTRATIONSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw REGISTRATIONSERVICEIMPLSERVICE_EXCEPTION;
        }
        return REGISTRATIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
